upstream rift_api {
    zone rift_api 64k;
    resolver 127.0.0.11 valid=5s ipv6=off;
    resolver_timeout 3s;
    server api:8000 resolve;
}

server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location /api/ {
        proxy_pass http://rift_api;
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
